require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false

IS_CI = ENV['APPCENTER_BUILD_ID'] || ENV['BITRISE_PROJECT_PATH']
PRODUCTION = IS_CI || ENV["PRODUCTION"] == "1"
FLIPPER_ENABLED = !IS_CI
FABRIC_ENABLED = false

$RNFirebaseAnalyticsWithoutAdIdSupport = true
# ENV['RCT_NEW_ARCH_ENABLED'] = '1'

def shared_pods
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :production => PRODUCTION,
    :flipper_configuration => FlipperConfiguration.enabled,
    :hermes_enabled => true,
    :fabric_enabled => FABRIC_ENABLED,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
end

target 'mobile' do
    shared_pods
end

#target 'mobile-staging' do
#    shared_pods
#end

#target 'appcenter-staging' do
#    shared_pods
#end


target 'appcenter-production' do
    shared_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.name == 'Debug'
        config.build_settings['OTHER_SWIFT_FLAGS'] = ['$(inherited)', '-Onone']
        config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Owholemodule'
      end
    end
  end
  react_native_post_install(installer)
  __apply_Xcode_12_5_M1_post_install_workaround(installer)
end
