name: Mobile Cache
description: "Pulls Mobile Node Modules Cache"

runs:
  using: composite

  steps:
    - name: Test with Chromedriver
      working-directory: .
      run: |
        curl -fL https://github.com/bitrise-io/bitrise/releases/download/1.49.0/bitrise-$(uname -s)-$(uname -m) > /usr/local/bin/bitrise
        chmod +x /usr/local/bin/bitrise
        bitrise setup
        bitrise run primary2
      shell: bash
