export const Project = {
  debug: false,
  api: 'http://localhost:4000/',
  apiAuth: '',
  ga: '',
  logoutRedirect: '/',
  loginRedirect: '/account',
  cognito: {
    region: '',
    userPoolId: '',
    userPoolWebClientId: '',
  },
  cognitoMobile: {
    region: '',
    userPoolId: '',
    userPoolWebClientId: '',
  },
  codepush: {
    android: {
      production: 'k8sD7nBA-5rr4wbirErJK5fGL81PZFaJpiPNN',
      staging: 'Wy71o_xKWJaeovpTUs4RWQ_Js6XwEoTp_FZHb',
    },
    ios: {
      production: 'k8sD7nBA-5rr4wbirErJK5fGL81PZFaJpiPNN',
      staging: 'Wy71o_xKWJaeovpTUs4RWQ_Js6XwEoTp_FZHb',
    },
  },
  firebase: {
    apiKey: 'AIzaSyCfV3iSjeJJmN7YbotjqlgrtcXTWg0l3d4',
    authDomain: 'plantkit-a8f60.firebaseapp.com',
    projectId: 'plantkit-a8f60',
    storageBucket: 'plantkit-a8f60.appspot.com',
    messagingSenderId: '92292927743',
    appId: '1:92292927743:web:fbe00f40064c6757783cca',
    measurementId: 'G-4MFB6SP1LN',
  },
  logs: {
    EVENTS: true,
    DATA: false,
    STORE: false,
    DISPATCHER: false,
    COGNITO: false,
    STORAGE: false,
    SERVER: false,
    API: false,
    PUSH_NOTIFICATIONS: false,
  },
  grecaptcher: '6Lc1mf4UAAAAAC6uZ0HaGJ3ufgwCXY4GFoNhMeBD',
  formly: 'boilerplate',
}
