name: Bitrise Setup

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: .

jobs:
  bitrise-setup:
    runs-on: macos-latest
    name: Bitrise Setup
    environment: production
      - name: Cloning repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
#      - name: Mobile Cache
#        uses: ./.github/actions/mobile-cache-action
      - name: Mobile Bitrise
        uses: ./.github/actions/mobile-bitrise-action
        with:
          ENV: prod
          PLATFORM: ios
          APPCENTER_ACCESS_TOKEN: ${{ secrets.APPCENTER_ACCESS_TOKEN }}
          APPCENTER_NAME: ${{ secrets.APPCENTER_NAME_IOS_PRODUCTION }}
          CODE_PUSH_ENVIRONMENT: Production
          CODE_PUSH_NAME: ${{ secrets.CODE_PUSH_NAME_IOS }}
          APPCENTER_NAME_ANDROID_PRODUCTION: ${{ secrets.APPCENTER_NAME_ANDROID_PRODUCTION }}
          APPCENTER_NAME_IOS_PRODUCTION: ${{ secrets.APPCENTER_NAME_IOS_PRODUCTION }}
